### ISSUE TITLE
README - Paths in step 6 not rendered correct

### ISSUE THREAD

**Issue by greiner-marcus-auticon** [shaovoon/using_csharp_lib_in_cpp#1]
You need to use double backslashes \\ to display a single backslash \ in the rendered README.

You should edit the README file and change:
* /AI "..\..\MFCwithCSharp\CSharpClass\bin\x86\Debug"
* /AI "..\..\MFCwithCSharp\CSharpClass\bin\x64\Debug"
* /AI "..\..\MFCwithCSharp\CSharpClass\bin\x86\Release"
* /AI "..\..\MFCwithCSharp\CSharpClass\bin\x64\Release"

to:
* /AI "..\\..\\MFCwithCSharp\\CSharpClass\\bin\\x86\\Debug"
* /AI "..\\..\\MFCwithCSharp\\CSharpClass\\bin\\x64\\Debug"
* /AI "..\\..\\MFCwithCSharp\\CSharpClass\\bin\\x86\\Release"
* /AI "..\\..\\MFCwithCSharp\\CSharpClass\\bin\\x64\\Release"

**Comment by shaovoon** [comment]
Hi, thanks alot! I did not know about this. It is fixed.

Thanks again!
